language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  domain: app.formette.com
  skip_cleanup: true
  local_dir: build
  on:
    branch: master

