language: node_js
node_js:
  - "7"
  - "lts/*"
cache:
  directories:
  - node_modules
script: npm run build
skip_cleanup: true
after_success:
  - surge --project ./path/to/your-project --domain app.formette.com
    