language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
script:
  - npm test
  - npm run build
skip_cleanup: true
deploy:
- provider: surge
  project: ./build/
  domain: app.formette.com 
  on: master
- provider: surge
  project: ./build/
  domain: beta.formette.com 
  on: develop