language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
  - /^greenkeeper/.*$/
script:
  - npm install
  - npm test
  - npm run build
deploy:
  - provider: surge
    project: ./build/
    domain: app.formette.com 
    skip_cleanup: true
    on:
      branch: master
  - provider: surge
    project: ./build/
    domain: beta.formette.com 
    skip_cleanup: true
    on:
      branch: develop