language: node_js
node_js:
  - "7"
  - "lts/*"
cache:
  directories:
  - node_modules
script: npm run build
after_success:
  deploy:
    provider: surge
    domain: app.formette.com
    skip_cleanup: true